### ISSUE TITLE
Hi Export & Excel scripts in pyTiba dont work as expected

### ISSUE THREAD

**Issue by tahaij** [tillbaum/pytiba#1]
attached are error log when running most of the pytiba scripts/commands
please advise it very possible I might be doing something wrong, as I am very new to pyrevit and Python in general
![pytiba](https://user-images.githubusercontent.com/35132143/47073494-75576300-d209-11e8-87de-c3fcb815ee6b.JPG)

**Comment by tillbaum** [comment]
it did not think that someone would download the scripts so soon.
